name: kazi_design_system
description: "A package to handle the Kazi Design System"
version: 0.3.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/svgs/

flutter_intl:
  enabled: true
  class_name: KaziLocalizations
  main_locale: en
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated
  use_deferred_loading: false
